name: Ping codeowners

on:
    push:
        branches:
            - main

jobs:
    ping-codeowners:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5

        - name: test
          run: make test
        